on:
  push:
    tags:
    - '*'

jobs:
  ts_client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM packages
        run: npm install --global yarn @bufbuild/buf @cosmology/telescope

      - name: Build protos
        run: |
          buf export ./proto/ --output=./exported_protos;

      - name: Transpile protos
        run: |
          telescope transpile --protoDirs ./exported_protos --outPath generated/src --useDefaults

      - name: Generate package
        run: |
          


